### ISSUE TITLE
Is there a way to change the output language?

### ISSUE THREAD

**Issue by MatQV** [chasebank87/unofficial-fabric-plugin#10]
Hi mate, first of all... thank you. This plugin has become something so amazing for me that I cannot describe how grateful I am. Really, thanks!

I was wondering... is there a way to force the output language of the fabrics? I guess I could translate the patterns and then add the translated ones into the main folder, but is there a simpler way to achieve this?

If not, it could be nice to be able to tell the plugin the output language and "force" the model to write in spanish.

Again, thank you, really! I hope this project keeps growing.

**Comment by chasebank87** [comment]
Yeah bud, I’ll see if I can add this today.

**Comment by chasebank87** [comment]
Hey I added this feature, now a user can select multiple patterns to run there data through in chronological order. This means that you can select extract_wisdom, and then a custom pattern you have made lets call it (translate_to_spanish). The plugin will send those two patterns to the API, and the API will run extract_wisdom first, and the run translate_to_spanish on the output from the first pattern.

I also added a feature in the settings view called Default Post Processing Pattern. This pattern will be ran after every run which is where you could put the translate_to_spanish pattern.

You will need to update the fabric connector also for this to work correctly:

https://github.com/chasebank87/fabric-connector/releases/tag/1.0.3

**Comment by MatQV** [comment]
> Hey I added this feature, now a user can select multiple patterns to run there data through in chronological order. This means that you can select extract_wisdom, and then a custom pattern you have made lets call it (translate_to_spanish). The plugin will send those two patterns to the API, and the API will run extract_wisdom first, and the run translate_to_spanish on the output from the first pattern.
> 
> 
> 
> I also added a feature in the settings view called Default Post Processing Pattern. This pattern will be ran after every run which is where you could put the translate_to_spanish pattern.
> 
> 
> 
> You will need to update the fabric connector also for this to work correctly:
> 
> 
> 
> https://github.com/chasebank87/fabric-connector/releases/tag/1.0.3

Holy sht man, THANKS! Will test this later today and give you any feedback I can ⚡️

**Comment by chasebank87** [comment]
No problem, anytime. Ill keep this open till I hear back. Cheers

**Comment by MatQV** [comment]
Ok, I'm going kinda crazy, I've downloaded some of the custom patterns using the download button you added, specifically the "extract_tutorial" and created the "custom patterns" folder on my obsidian. 

BUT when selecting a pattern (in the plugin sidebar) I cannot select any custom patterns, just the basic ones, is that ok? Or am I missing something?

Here are some screenshots:

![SS - 000113](https://github.com/user-attachments/assets/afeaddba-e64d-4fcc-8249-063a8c4251d1)
![SS - 000115](https://github.com/user-attachments/assets/b07390e1-d643-4c06-aa37-b8c8d1d44d35)
![SS - 000114](https://github.com/user-attachments/assets/ecbe5bf3-687c-419f-8754-a55493ab3da1)

What am I missing? I wanted to test the custom pattern before creating the "translate_to_spanish" one.

Thanks!

**Comment by MatQV** [comment]
> Ok, I'm going kinda crazy, I've downloaded some of the custom patterns using the download button you added, specifically the "extract_tutorial" and created the "custom patterns" folder on my obsidian.
> 
> BUT when selecting a pattern (in the plugin sidebar) I cannot select any custom patterns, just the basic ones, is that ok? Or am I missing something?
> 
> Here are some screenshots:
> 
> ![SS - 000113](https://private-user-images.githubusercontent.com/46688295/354849424-afeaddba-e64d-4fcc-8249-063a8c4251d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MjcyMzgsIm5iZiI6MTcyMjcyNjkzOCwicGF0aCI6Ii80NjY4ODI5NS8zNTQ4NDk0MjQtYWZlYWRkYmEtZTY0ZC00ZmNjLTgyNDktMDYzYThjNDI1MWQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIzMTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MDA3NTdhYTE5MTlkOGEyZTUyOWVlYWY4YTIwZjg4NDE5NjA5OWQwMWI5NmRjMDIyZjA0NzQxM2VjZDllOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89EPG0298Ia1Fv8RZhMiz1YpHOHGCGstDEuh8TVYJgE) ![SS - 000115](https://private-user-images.githubusercontent.com/46688295/354849440-b07390e1-d643-4c06-aa37-b8c8d1d44d35.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MjcyMzgsIm5iZiI6MTcyMjcyNjkzOCwicGF0aCI6Ii80NjY4ODI5NS8zNTQ4NDk0NDAtYjA3MzkwZTEtZDY0My00YzA2LWFhMzctYjhjOGQxZDQ0ZDM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIzMTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjdiMDcwMjA3MTc2Mjg0MjQ3ZGNmYjNhMDM4MmIzYTQzZTQxODVhYzNlMDM4MzM0MzgwOTJjNWMxMDhkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WZvuVlMA6Ipi-QMMbeJHFCt6VIl2u17UCznGaUiAKyw) ![SS - 000114](https://private-user-images.githubusercontent.com/46688295/354849441-ecbe5bf3-687c-419f-8754-a55493ab3da1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MjcyMzgsIm5iZiI6MTcyMjcyNjkzOCwicGF0aCI6Ii80NjY4ODI5NS8zNTQ4NDk0NDEtZWNiZTViZjMtNjg3Yy00MTlmLTg3NTQtYTU1NDkzYWIzZGExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIzMTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmM2N2U0ODgzMWJkNDIyYWM5YjI3YjEzYzc1ZmJmMGE4OTg4ZTMwYzllYmUyMjY5N2NkNmJlMDU4ZWIwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ifQywV2nVaivg2BRfyy2qAajRgh_zrDqiajQeLyOV4)
> 
> What am I missing? I wanted to test the custom pattern before creating the "translate_to_spanish" one.
> 
> Thanks!

I misspelled tutorial on the screenshot, but it doesnt work even with the right words added haha

**Comment by MatQV** [comment]
Oh shit, I just saw and clicked the freaking arrow going up the cloud icon and it worked. 

Maybe it's just my perception, but the buttons aren't very logical just by their icon; it might be more user-friendly if they had a descriptive name!

**Comment by chasebank87** [comment]
Yeah I considered making them text instead of icons, but they just look cluttered. However there should be a tooltip when you hover over the button. I’ll look into making it more clear.

**Comment by MatQV** [comment]
I can confirm the translations is working like a charm. Cant believe you helped me with this so fast. I'm 100% donating right now. Thanks, really.
