### ISSUE TITLE
Youtube detection not working, any way to force it?

### ISSUE THREAD

**Issue by MatQV** [chasebank87/unofficial-fabric-plugin#13]
Hello again!

I think I might be missing something about YouTube link detection. I’ve never tried using it before, so I did a little test by copying a YouTube URL into an empty note and activating the "YouTube links" button. However, I got two different results:

1. It randomly selected a video about OpenAI and returned the "extract_wisdom" pattern with that information instead of the video I added.
2. It mentioned that it couldn’t view YouTube content directly, similar to a default ChatGPT answer.

Maybe I’m not quite understanding how it works? I’d really appreciate your help!

**Comment by chasebank87** [comment]
In fabric there is a YouTube api key, do you have that key entered? Also the url doesn’t have to be in a not it can simply be in your clipboard if you click the clipboard button.Sent from my iPhoneOn Aug 10, 2024, at 6:04 PM, MatQV ***@***.***> wrote:﻿
Hello again!
I think I might be missing something about YouTube link detection. I’ve never tried using it before, so I did a little test by copying a YouTube URL into an empty note and activating the "YouTube links" button. However, I got two different results:

It randomly selected a video about OpenAI and returned the "extract_wisdom" pattern with that information instead of the video I added.
It mentioned that it couldn’t view YouTube content directly, similar to a default ChatGPT answer.

Maybe I’m not quite understanding how it works? I’d really appreciate your help!

**Comment by chasebank87** [comment]
When you have one or more youtube links in a note or your clipboard, a modal should pop up if the youtube link detection toggle is on. From that menu you can choose the link you want to transcribe and click run. If you click skip, it will skip transcribing and just run the current note or clipboard through your pattern.

For this to work though you have to have a youtube API key in your fabric .env file.

**Comment by MatQV** [comment]
Yeah I have added the Youtube API but for some reason it keeps failing, look, I tried using YT directly from my console, and I'm still getting that weird OpenAI info:

![SS - 000164@2x](https://github.com/user-attachments/assets/9bb61b2a-96ff-420f-8a09-ebfac0c30e91)

Weird stuff, I reinstalled Fabric, added my API keys, but still getting that.

Sorry to bother!

**Comment by chasebank87** [comment]
Weird, I just checked that link on mine and it worked:

# SUMMARY
Anubhav presents Llama-FS, an AI-powered file manager that organizes chaotic download folders automatically and intelligently.

# IDEAS:
- Llama-FS transforms chaotic download folders into perfectly organized structures.
- Powered by Llama 3 and Groq API, Llama-FS is blazingly fast.
- The tool renames files and suggests proper directory structures.
- Created by Alex Thomas and Ajay during the Llama 3 hackathon.
- Llama-FS reads file context to classify, rename, and organize them.
- The tool can handle various file types like screenshots, research papers, and text files.
- Users can accept or reject the changes suggested by Llama-FS.
- Setup involves cloning the GitHub repository and installing dependencies.
- Requires Python 3.10 or higher and pip package for installation.
- Users need to sign up on Groq to get an API key for the tool.
- The API key should be kept secret and not shared with others.
- Llama-FS can also run offline using Olama Moondream in incognito mode.
- The server is run using FastAPI, and the desktop app uses Electron and React.
- The desktop application requires npm to install dependencies and start.
- Users specify the folder path, click a wand icon, and wait for organization.
- Summaries and renamed file structures are displayed for each file.
- The video includes a demo of Llama-FS organizing a cluttered folder.
- Anubhav encourages viewers to like, share, and subscribe for more AI content.
- The tool aims to save time and reduce manual file organization efforts.
- Llama-FS provides a summary of changes before finalizing them.

# INSIGHTS:
- AI can significantly reduce manual effort in organizing digital clutter.
- Context-aware file management systems can improve productivity.
- Combining AI with user-friendly interfaces enhances technology adoption.
- Keeping API keys secure is crucial for maintaining data privacy.
- Offline modes for AI tools address privacy concerns effectively.
- Open-source projects foster innovation through community collaboration.
- Automating mundane tasks allows users to focus on more meaningful work.
- Real-time file organization can streamline digital workflows.
- User acceptance of AI-driven changes ensures control over automation.
- Integrating multiple technologies (AI, APIs, FastAPI) creates robust solutions.

# QUOTES:
- "Imagine if there was a way to organize all of these files automatically, effortlessly, and intelligently."
- "Meet the ultimate file manager, Llama-FS, powered by Llama 3 and blazingly fast with Groq API."
- "Searching for a specific file in this feels like finding a needle in a haystack."
- "Llama-FS reads the context and classifies them, renames them, and organizes them in a tree structure."
- "This project was created by Alex Thomas and Ajay as part of the Llama 3 hackathon."
- "You can see here that it has also renamed the files from file 1 to this thing."
- "It renamed it from a big number and a big version to actually something that makes sense."
- "You can install Python 3.10 using Miniconda for which I will leave the link for Windows, Mac, and Linux."
- "Make sure to not share these API secret keys with anybody."
- "Using Groq API will push all your content and data to online servers."
- "In case if you don't want to send the files and content to online servers, you can also install Olama Moondream."
- "Once the application is open, all you need to do is to mention your path of the folder with all the clutter."
- "In just a few simple steps, you have transformed your cluttered download folder into a neatly organized folder by Llama-FS."
- "If you found this video helpful, make sure to like and share it with your friends who want to declutter their files too."
- "Don't forget to subscribe to our channel for more such content on AI and ML."

# HABITS:
- Regularly organize digital files using automated tools like Llama-FS.
- Keep API keys secure and private to maintain data integrity.
- Use open-source projects to stay updated with technological advancements.
- Follow step-by-step setup instructions for new software tools.
- Utilize offline modes for privacy-sensitive tasks.

# FACTS:
- Llama-FS is powered by Llama 3 and Groq API for fast performance.
- The tool was created during the Llama 3 hackathon by Alex Thomas and Ajay.
- Requires Python 3.10 or higher for installation.
- Users need an API key from Groq to use the tool online.
- Olama Moondream allows running Llama-FS offline in incognito mode.

# REFERENCES:
- GitHub repository for Llama-FS
- Miniconda for installing Python 3.10
- Groq API console for obtaining API keys
- FastAPI for running the server
- Electron and React for the desktop application

# ONE-SENTENCE TAKEAWAY
Llama-FS automates file organization using AI, transforming chaotic folders into neatly structured directories effortlessly.

# RECOMMENDATIONS:
- Use Llama-FS to automate organizing your download folders efficiently.
- Keep your API keys secure to protect your data privacy.
- Follow detailed setup instructions for smooth installation of new tools.
- Utilize offline modes for privacy-sensitive tasks with AI tools.
- Regularly update your software tools to benefit from new features.%    


Maybe create a new key and check the instructions again for creating the key.

**Comment by chasebank87** [comment]
Maybe create a new key and check the instructions again for creating the key.

**Comment by MatQV** [comment]
Ok, I made it work inside the console adding quotes around the youtube url, but still wont work inside of obsidian. Hmm, will test a few things and get back!

**Comment by chasebank87** [comment]
Please do, it could be a bug. Turn on debugging and post them here.

**Comment by MatQV** [comment]
Here's using with a link inside a note:


https://github.com/user-attachments/assets/98d83b4b-5ac6-4951-83f3-1fa61fdcfe45

Here's when using just the clipboard:


https://github.com/user-attachments/assets/1d065ddf-5096-4c55-80ac-b184765157c9

**Comment by MatQV** [comment]
Debug Console:

## Obsidian Developer Console

plugin:custom-sort:42 loading custom-sort v2.1.12
plugin:recent-files-obsidian:265 Recent Files: Loading plugin v1.4.1
plugin:obsidian-paste-image-rename:465 Plugin loading: obsidian-paste-image-rename 1.6.1 BUILD_ENV=production
plugin:unofficial-fabric-integration:1004 [Fabric] Debug mode enabled
plugin:unofficial-fabric-integration:986 [Fabric Debug] Registering custom patterns folder watcher
plugin:unofficial-fabric-integration:986 [Fabric Debug] Watching for deletions in: Templates/Patterns/
plugin:unofficial-fabric-integration:986 [Fabric Debug] Patterns loaded: Array(134)
plugin:unofficial-fabric-integration:986 [Fabric Debug] Models loaded: Array(5)
plugin:unofficial-fabric-integration:986 [Fabric Debug] Registering custom patterns folder watcher
plugin:unofficial-fabric-integration:986 [Fabric Debug] Watching for deletions in: Templates/Patterns/
plugin:unofficial-fabric-integration:986 [Fabric Debug] File deletion detected: Ideas Vault/Fabric/Youtube Test.md
plugin:unofficial-fabric-integration:986 [Fabric Debug] Custom patterns folder: Templates/Patterns
plugin:unofficial-fabric-integration:986 [Fabric Debug] File is not in the custom patterns folder
plugin:unofficial-fabric-integration:986 [Fabric Debug] File deletion detected: Ideas Vault/Fabric/Youtube Test (1).md
plugin:unofficial-fabric-integration:986 [Fabric Debug] Custom patterns folder: Templates/Patterns
plugin:unofficial-fabric-integration:986 [Fabric Debug] File is not in the custom patterns folder
plugin:unofficial-fabric-integration:986 [Fabric Debug] File deletion detected: Ideas Vault/Fabric/YoutubeTest.md
plugin:unofficial-fabric-integration:986 [Fabric Debug] Custom patterns folder: Templates/Patterns
plugin:unofficial-fabric-integration:986 [Fabric Debug] File is not in the custom patterns folder

**Comment by chasebank87** [comment]
Ahhh, the detection isnt working, and sending the url straight to fabric instead of rerouting through the YT route. This is definitely a bug. Going to look into it. Probably an issue with the regex or something.

**Comment by chasebank87** [comment]
Hey! Sorry for the delay. I have fixed this issue with the most recent update. The problem was that you had audio links turned off which is where the bug was. The logic is fixed so you should be able to have audio files off and youtube link detection should work.

**Comment by MatQV** [comment]
Will test it later today and get back to you! Thanks for your work mate! I really love what you've done.
