### ISSUE TITLE
Can't use Patterns

### ISSUE THREAD

**Issue by Beingpax** [chasebank87/unofficial-fabric-plugin#15]
![20 at 19 02 01](https://github.com/user-attachments/assets/16c6406b-4ded-4154-8dcf-764d86d2856c)
I'm able to set it up finally but can't select any patterns. I can add a new pattern in my vault and sync it to the drive but no patterns are shown to select .

**Comment by chasebank87** [comment]
Hello! Do two things for me, first go into the plugin settings and turn on debug mode. Once you do that go click the refresh patterns button. In the web development console window post what errors you get.

Second, go to the API docs url. And run the patterns endpoint after authenticating with your key. You should get a list of patterns, if you don't your fabric installation must be in a non standard location. If so where is your fabric patterns folder?

**Comment by Beingpax** [comment]
fabric patterns folder is inside /Users/beingpax/.config/fabric/patterns folder. 

![20 at 20 16 08@2x](https://github.com/user-attachments/assets/43b321e1-1df2-47f7-8b4c-5e229891b8ee)
This is from Obsidian console. 

I don't fully understand your information. But, this is what I did, I opened the API docs url and added my API by clicking on authentication. After that I clicke on try it out under patterns. But didn't do anything
![20 at 20 19 50](https://github.com/user-attachments/assets/9ed5f220-e94f-4b1f-a47e-84d1ae338014)

**Comment by chasebank87** [comment]
That folder is the standard location. But wait, I thought you replied that you fixed it?Sent from my iPhoneOn Aug 20, 2024, at 10:38 AM, Beingpax ***@***.***> wrote:﻿
fabric patterns folder is inside /Users/beingpax/.config/fabric/patterns folder.
***@***.*** (view on web)
This is from Obsidian console.
I don't fully understand your information. But, this is what I did, I opened the API docs url and added my API by clicking on authentication. After that I clicke on try it out under patterns. But didn't do anything
20.at.20.19.50.gif (view on web)

**Comment by Beingpax** [comment]
No. I haven't fixed it. I'm just confused what I'm doing wrong

**Comment by chasebank87** [comment]
Oh I see, you had a separate issue with the API url. My bad. Okay can you check in security from your system settings and see under files and folders if fabric connector has full disk access?Sent from my iPhoneOn Aug 20, 2024, at 11:05 AM, Chase Elder ***@***.***> wrote:﻿That folder is the standard location. But wait, I thought you replied that you fixed it?Sent from my iPhoneOn Aug 20, 2024, at 10:38 AM, Beingpax ***@***.***> wrote:﻿
fabric patterns folder is inside /Users/beingpax/.config/fabric/patterns folder.
***@***.*** (view on web)
This is from Obsidian console.
I don't fully understand your information. But, this is what I did, I opened the API docs url and added my API by clicking on authentication. After that I clicke on try it out under patterns. But didn't do anything
20.at.20.19.50.gif (view on web)

**Comment by chasebank87** [comment]
Are you ARM or Intel?Sent from my iPhoneOn Aug 20, 2024, at 11:10 AM, Beingpax ***@***.***> wrote:﻿
No. I haven't fixed it. I'm just confused what I'm doing wrong

**Comment by Beingpax** [comment]
I'm on ARM

**Comment by chasebank87** [comment]
I have to available right now, if you want to hop on a meeting to look at this.Sent from my iPhoneOn Aug 20, 2024, at 11:14 AM, Beingpax ***@***.***> wrote:﻿
I'm on ARM

**Comment by Beingpax** [comment]
sure

**Comment by chasebank87** [comment]
ElderCloudcloud.theelders.ccSent from my iPhoneOn Aug 20, 2024, at 11:19 AM, Beingpax ***@***.***> wrote:﻿
sure

**Comment by Beingpax** [comment]
What's that?

**Comment by chasebank87** [comment]
https://cloud.theelders.cc/call/8sqtnrop

**Comment by Beingpax** [comment]
![20 at 21 08 16@2x](https://github.com/user-attachments/assets/42ad57b9-a011-4065-b852-7335ee3bd47a)

**Comment by chasebank87** [comment]
Ahh what country are you in?

**Comment by Beingpax** [comment]
Nepal

**Comment by chasebank87** [comment]
Okay one sec.

**Comment by Beingpax** [comment]
Sure

**Comment by chasebank87** [comment]
Okay try again

**Comment by chasebank87** [comment]
https://cloud.theelders.cc/call/8sqtnrop

**Comment by chasebank87** [comment]
Great talking to you, cheers.

**Comment by Beingpax** [comment]
Thanks so much for the help.

**Comment by chasebank87** [comment]
Hey! I added support for Fabric 2.0 (GO), just update the plugin, install the new connector, and in the plugin settings turn on fabric 2.0 compatibility.I would change over to this if you are wanting to use models other than OpenAI, older fabric versions don’t do well with that especially local models.Sent from my iPhoneOn Aug 20, 2024, at 12:59 PM, Beingpax ***@***.***> wrote:﻿
Thanks so much for the help.
