### ISSUE TITLE
Multiple Pattern workflow

### ISSUE THREAD

**Issue by Beingpax** [chasebank87/unofficial-fabric-plugin#16]

**Comment by chasebank87** [comment]
Yeah, it will run the selected input through the first pattern in the list, then it will send the output of the first pattern through to the second pattern and so on. I think I want to add an option that will change the behavior to just creating a file with the output of the original source with each pattern.For instance one note gets created when summary and extract wisdom are selected and in the note there would be summary at the top, and extract wisdom at the bottom.Sent from my iPhoneOn Aug 25, 2024, at 12:17 PM, Beingpax ***@***.***> wrote:﻿
Closed #16 as completed.

**Comment by chasebank87** [comment]
@Beingpax Hey couldn’t find any other way of getting a hold of you but I wanted to let you know I caught your latest video, thanks for the plug.

wanted to let you know if you do decide to make that video on the plugin, you should first take a look at the new plugin. Mesh-ai in my repo, it’s not in the community repo yet still waiting for approval but you can get it using the BRAT plugin, make sure you use the post-release branch. Let me know if you need assistance, also if you had any ideas you want to add to the plugin to help on your video let me know. 

Cheers
